config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  mount Upmin::Engine => '/admin'
  devise_for :users
  resources :users
  resources :projects
  resources :companies
end

app/models/company.rb
class Company < ActiveRecord::Base
    has_many :users # a funeral service company may have numerous users
end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :user
    
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :company # a user can (not required to) be associated with any company
  has_many :projects
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    def index
        @companies = Company.all
    end
    
    def show
        @company = Company.find(params[:id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    
    def index
        @projects = Project.all
    end
    
    def show
        @project = Project.find(params[:id])
    end
    
    def new
        @project = Project.new
        @project.user_id = current_user.id
        
        respond_to do |format|
            format.html # new.html.erb
            format.xml  { render :xml => @project }
        end
    end
    
    def create
        binding.pry
        @project = Project.new(project_params)

        respond_to do |format|
          if @project.save
            format.html { redirect_to(projects_path, :notice => 'Project was successfully created.') }
            format.xml  { render :xml => @project, :status => :created, :location => @project }
          else
            format.html { render :action => "new" }
            format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
          end
        end
    end
    
    private
    
    def project_params
       p = params.require(:project).permit(:decedent, :due_date) 
       p[:user_id] = current_user.id
       p
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @projects = Project.where(:user_id => params[:id])
    #binding.pry
    
    ##### Below is basic authorization, preventing the logged in user to see the profile of any other person
    #unless @user == current_user
    #  redirect_to :back, :alert => "Access denied."
    #end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/projects_controller_helper.rb
module ProjectsControllerHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
    
    # since this doesn't actually run any business logic, but instead simply converts
    # existing time data into a more readable format, it belongs in the helper instead of the model
    def due(project)
       time_ahead_in_words(project.due_date)
    end
    
    def timeago(time, options = {})
     options[:class] ||= "timeago"
     content_tag(
       :time,
       time.to_s,
       options.merge(datetime: time.getutc.iso8601)
     ) if time
    end
    
end

app/helpers/time.rb
module TimeHelper
    
   def timeago(time, options = {})
     options[:class] ||= "timeago"
     content_tag(
       :time,
       time.to_s,
       options.merge(datetime: time.getutc.iso8601)
     ) if time
   end
   
end

app/views/companies/_company.html.erb
<td><%= link_to company.name, company %></td>
<td><%= "Number of Contacts: #{company.users.count}" %></td>

app/views/companies/index.html.erb
<div class="container">
  <div class="row">
    <h3>Companies</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @companies.each do |company| %>
            <tr>
              <%= render company %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Projects', projects_path %></li>
  <li><%= link_to 'Companies', companies_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Swmapp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Swmapp" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <%= javascript_tag do %>
     $(function() {
       $("time.timeago").timeago();
     });
   <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label "Decedent Name" %>
    <%= f.text_field :decedent %><br>
    
    <%= f.label "Select Due Date" %>
    <%= f.datetime_field :due_date %><br>
    
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<td><%= link_to project.decedent, project %></td>
<td><%= link_to project.user.name, project.user %></td>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
    <h3>Projects</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <%= render project %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h3>Project</h3>
<p id="notice"><%= notice %></p>
<p>ID: <%= @project.id %></p>
<p>Decedent: <%= @project.decedent %></p>
<p>Due: <%= timeago(@project.due_date) %> </p>
<p>Contact: <%= link_to @project.user.name, @project.user %></p>
<p>Created: <%= timeago(@project.created_at) %></p>
<p>Last Updated: <%= timeago(@project.updated_at) %></p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/users/_project.html.erb
<td><%= project.id %></td>
<td><%= project.decedent %></td>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Company: <%= @user.company.name if @user.company %></p>
<table class="table">
    <tbody>
     <tr>
         <td>Decedent</td>
         <td>Due Date</td>
     </tr>    
      <% @projects.each do |project| %>
        <tr>
            <td><%= link_to project.decedent, project %></td>
            <td><%= timeago(project.due_date) %></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>